//
//  SAWebExtensionHandler.m
//  ScreenActionsWebExtension
//
//  Created by . . on 9/22/25.
//
//  Objective-C principal that **conforms** to NSExtensionRequestHandling
//  and forwards to the Swift handler.
//

#import <Foundation/Foundation.h>
#import <SafariServices/SafariServices.h>
#import "ScreenActionsWebExtension-Swift.h" // generated by Swift

@interface SAWebExtensionHandler : NSObject <NSExtensionRequestHandling>
@end

@implementation SAWebExtensionHandler
- (void)beginRequestWithExtensionContext:(NSExtensionContext *)context
{
    SafariWebExtensionHandler *swiftHandler = [SafariWebExtensionHandler new];
    [swiftHandler beginRequestWithExtensionContext:context];
}
@end
